---
network:
  version: 2
  renderer: NetworkManager
  ethernets:
    enp0s3:
      dhcp4: yes
    enp0s8:
      dhcp4: no
      addresses:
        - 192.168.14.130/24
      routes:
        - to: default
          via: 192.168.14.2
      nameservers:
        addresses:
          - 1.1.1.1
          - 8.8.8.8
